name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Release
        run: dotnet build --configuration Release --no-restore /p:TreatWarningsAsErrors=false

      # NuGet パッケージのビルド
      - name: Pack NuGet packages
        run: |
          mkdir -p packages
          dotnet pack src/DocumentFileManager/DocumentFileManager.csproj --configuration Release --no-build --output ./packages
          dotnet pack src/DocumentFileManager.Infrastructure/DocumentFileManager.Infrastructure.csproj --configuration Release --no-build --output ./packages
          dotnet pack src/DocumentFileManager.Viewer/DocumentFileManager.Viewer.csproj --configuration Release --no-build --output ./packages
          dotnet pack src/DocumentFileManager.UI/DocumentFileManager.UI.csproj --configuration Release --no-build --output ./packages
          dotnet pack src/DocumentFileManager.Complete/DocumentFileManager.Complete.csproj --configuration Release --no-build --output ./packages
        shell: bash

      # GitHub Packagesに公開
      - name: Publish to GitHub Packages
        run: |
          Get-ChildItem -Path ./packages -Filter *.nupkg | ForEach-Object {
            dotnet nuget push $_.FullName --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
          }
        shell: pwsh

      - name: Publish UI Application
        run: dotnet publish src/DocumentFileManager.UI/DocumentFileManager.UI.csproj -c Release -o ./publish/UI

      - name: Publish Viewer Application
        run: dotnet publish src/DocumentFileManager.Viewer/DocumentFileManager.Viewer.csproj -c Release -o ./publish/Viewer

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: |
            ./packages/*.nupkg
